<a href="https://colab.research.google.com/github/Prithviraj2706/DS-training/blob/main/Python_Basic_coding_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
print("Python, Be good to me")

Python, Be good to me


In [27]:
#COMMENT

In [28]:
print("RAJ")

RAJ


In [29]:
a=2
print(a)

2


In [30]:
type(a)

int

In [31]:
d= 'True'
type(d)

str

In [32]:
10+20

30

In [33]:
20-5

15

In [34]:
60/10

6.0

In [35]:
60*20

1200

In [36]:
64^2

66

In [37]:
import math
math.sqrt(64)

8.0

In [38]:

8==8

True

In [39]:
8==9

False

In [40]:
8!=9

True

In [41]:
7<6

False

In [42]:
10>5

True

In [43]:
i=0
while i<10:
  print(i)
  i=i+1

0
1
2
3
4
5
6
7
8
9


In [44]:
i=0
while i<10:
  print(i)
  i=i+1
print('good job')

0
1
2
3
4
5
6
7
8
9
good job


In [45]:
for k in range(10):
  print(k)


0
1
2
3
4
5
6
7
8
9


In [46]:
list1=['prithvi',22,'pass']
for raj in list1:
  print(raj)

prithvi
22
pass


In [47]:
import numpy as np
from numpy.random import randn

In [48]:
x=randn()
x

-0.7341708270959227

In [49]:
result=None
x=randn()
if x>1:
  result='x is greater than 1'
print(x)
print(result)


0.6109580095421274
None


In [50]:
x=randn()
if x>1:
  result='x is greater than 1'
print(x)
print(result)


1.581181140127337
x is greater than 1


In [51]:
result= None
x=randn()
if x>1:
  result='x is greater than 1'
print(x)
print(result)


-0.5247812606650957
None


In [52]:
x=randn()
if x>1:
  result='x is greater than 1'
else:
   result='x is lesser than 1' 
print(x)
print(result)

-0.5769816942065199
x is lesser than 1


In [53]:
x=randn()
if x>1:
  result='x is greater than 1'
else:
   result='x is lesser than 1' 
print(x)
print(result)

0.14168602694189716
x is lesser than 1


In [54]:
x=randn()
if x>1:
  result='x is greater than 1'
elif x>=-1:
  result='x is between -1 and 1'
else:
  result='x is less than -1'
print(x)
print(result)      

-1.0509408047702804
x is less than -1


In [55]:
x=randn()
if x>1:
  result='x is greater than 1'
elif x>=-1:
  result='x is between -1 and 1'
else:
  result='x is less than -1'
print(x)
print(result)      

-0.38998936308492715
x is between -1 and 1


In [56]:
x=randn()
if x>1:
  result='x is greater than 1'
elif x>=-1:
  result='x is between -1 and 1'
else:
  result='x is less than -1'
print(x)
print(result)      

-0.5500063704129121
x is between -1 and 1


In [57]:
x=randn()
if x>1:
  result='x is greater than 1'
elif x>=-1:
  result='x is between -1 and 1'
else:
  result='x is less than -1'
print('good job')
print(x)
print(result)      

good job
0.5950955007629888
x is between -1 and 1


In [58]:
x=randn()
if x>1:
  result='x is greater than 1'
elif x>=-1:
  result='x is between -1 and 1'
else:
  result='x is less than -1'
  print('good job')
print(x)
print(result)   

0.7195039574070654
x is between -1 and 1


In [59]:
list2=['raj',20,45.632,True]
list2[2]

45.632

In [60]:
list2[-2]

45.632

In [61]:
list3=['prithvi',50,list2]

In [62]:
list3

['prithvi', 50, ['raj', 20, 45.632, True]]

In [63]:
list3[1]=90

In [64]:
list3

['prithvi', 90, ['raj', 20, 45.632, True]]

In [65]:
print(list3)

['prithvi', 90, ['raj', 20, 45.632, True]]


In [66]:
list4=list3+list2

In [67]:
print(list4)

['prithvi', 90, ['raj', 20, 45.632, True], 'raj', 20, 45.632, True]


In [68]:
letters=['a','b','c','d','e','f','g','h','i','j']

In [69]:
letters[1:6]

['b', 'c', 'd', 'e', 'f']

In [70]:
letters[-1]

'j'

In [71]:
letters[:-1]

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']

In [72]:
letters[1:8:3]  #start index:end index:interval

['b', 'e', 'h']

In [73]:
letters[-9:-1:2]

['b', 'd', 'f', 'h']

In [74]:
letters[1::2]

['b', 'd', 'f', 'h', 'j']

In [75]:
letters[::3]

['a', 'd', 'g', 'j']

In [76]:
letters[7:]

['h', 'i', 'j']

In [77]:
letters[::-1]

['j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [80]:
tuple1=(56,72,'raj')
tuple1[1]

72

In [84]:
tuple1[1]= 80

TypeError: ignored

In [86]:
list5=list(range(30,41))

In [87]:
list5

[30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

In [88]:
type(list5)

list

In [89]:
len(list5)

11

In [90]:
max(list5)

40

In [91]:
min(list5)

30

In [93]:
max(50.6,45.23)

50.6

In [94]:
max('prithviraj')

'v'

In [95]:
min('prithviraj')

'a'

In [96]:
list6=[10,"raj",56.23,True]
a= np.array(list6)
a

array(['10', 'raj', '56.23', 'True'], dtype='<U32')

In [97]:
list7=[10,"raj",56.23,True]
b= np.array(list7)
b

array(['10', 'raj', '56.23', 'True'], dtype='<U32')

In [98]:
list8=[10,56.23,True]
c= np.array(list8)
c

array([10.  , 56.23,  1.  ])

In [99]:
list9=[10,True]
d= np.array(list9)
d

array([10,  1])

In [100]:
list10=[True]
e= np.array(list10)
e

array([ True])

In [78]:
list3

['prithvi', 90, ['raj', 20, 45.632, True]]